# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for MetaTag Genie MCP server
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files and install dependencies without running scripts
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Production image
FROM node:18-alpine
WORKDIR /app

# Copy built artifacts and production dependencies
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./

# Install production dependencies only
RUN npm ci --omit=dev --ignore-scripts

# Default command
CMD ["node", "dist/main.js"]
